folder: fra/ # The folder that required to be parsed
httpsOnly: false # If you want enforce only HTTPS links
pullRequestReview: false # If you want a nice review in your pull requests
ignore: 
  urls: # Array of url to ignore, most of them return a 403 error...
    - https://berwick.fr/
    - https://links.berwick.fr/*
    - https://dl.acm.org/*
    - https://doi.org/*
    - https://www.cairn.info/*
    - https://rootly.com/
    - https://www.sciencedirect.com/topics/neuroscience/root-cause-analysis
    - https://www.ssi.gouv.fr/*
    - https://www.researchgate.net/publication/266394032_A_Theory_of_Blame
    - https://www.cloudflare.com/learning/access-management/castle-and-moat-network-security/
    - https://www.ncia.nato.int/about-us/newsroom/the-nci-agencye28099s-software-factory-a-new-way-to-collaborate-with-industry.html
    - https://gitlab.com/gitlab-org/gitlab/-/value_stream_analytics # Replaced by new concept https://docs.gitlab.com/ee/user/analytics/value_streams_dashboard.html
    - https://gitlab.biterg.io/app/kibana#/dashboard/3e297c20-622c-11e9-8638-c11f0f1aa3fa
    - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7959608/
delay:
  'https://gitlab.com': 500 # Perform a pause of 500ms at each call matching the url
  'https://gitlab.biterg.io': 1000
