name: Markdownlint

on:
  push:
  pull_request:

jobs:

  check-404-links:
    name: Check for 404 links
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 404 Links
        uses: atalent-labs/404-links@3.1.4

  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-22.04
    needs: check-404-links

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint all MD files
      uses: docker://avtodev/markdown-lint:v1 # fastest way
      with:
        args: '.'
