name: Markdown checks

on:
  push:
  pull_request:

jobs:

  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Lint all MD files
      uses: docker://avtodev/markdown-lint:v1 # fastest way
      with:
        args: '.'
