name: Markdownlint

on:
  push:
  pull_request:

jobs:

  markdownlint:
    name: Markdownlint
    runs-on: ubuntu-22.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint changelog file
      uses: docker://avtodev/markdown-lint:v1 # fastest way
